package com.organization.bootchampweb.rest;

import com.organization.bootchampweb.model.User;
import com.organization.bootchampweb.service.SecurePassword;
import com.organization.bootchampweb.service.VerifyExistence;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import org.springframework.validation.beanvalidation.MethodValidationInterceptor;
import org.springframework.web.bind.annotation.*;

import org.springframework.web.bind.annotation.RequestMapping;

import com.organization.bootchampweb.dao.UserRepository;

import javax.validation.Valid;
import java.util.Optional;

@RestController    // This means that this class is a Controller
@RequestMapping(path="/user") // This means URL's start with /demo (after Application path)
public class UserController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;
    @Autowired
    private SecurePassword securePassword;
    @Autowired
    VerifyExistence verifyExistence;

    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
    @GetMapping(path = "/getById")
    public @ResponseBody User getById(@RequestParam Long id){
        return userRepository.findById(id);
    }
    @GetMapping(path = "/getByEmail")
    public @ResponseBody User getByEmail(@RequestParam String email){
        return userRepository.findByEmail(email);
    }
    @GetMapping(path = "/getByUserName")
    public @ResponseBody User getByUserName(@RequestParam String useraName){
        return userRepository.findByUserName(useraName);
    }


    @PostMapping("/addUser")
    public User createUser(@Valid @RequestBody User user){
    verifyExistence.verifyByEmail(userRepository,user);
    verifyExistence.verifyByUserName(userRepository,user);
    String newPass=securePassword.securePassword(user.getPassword(), "Base64");
    user.setPassword(newPass);
    return userRepository.save(user);
    }
    @DeleteMapping("/deleteById")
    public @ResponseBody void deleteById(@RequestParam Integer id){
        userRepository.deleteById(id);
    }

    @PutMapping(path="/modify")
    public @ResponseBody User modifyUser(@Valid @RequestBody User user ) {
        //verifyExistence.MethodValidationPostProcessor(userRepository, user);
        verifyExistence.correctUserModifyUserName(userRepository, user);
        verifyExistence.correctUserModifyEmail(userRepository, user);
        String newPass=securePassword.securePassword(user.getPassword(), "Base64");
        user.setPassword(newPass);
        return userRepository.save(user);

    }
}